const micronutriments = [
	{
	  description: "Multivitamins",
	  price: 28,
	  quantity: 180,
	  monthlyServingsNeed: 30,
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/now/now03881/w/6.jpg",
	},	
	{
	  description: "Omega 3",
	  price: 21,
	  quantity: 180,
	  monthlyServingsNeed: 120,
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/now/now01662/l/4.jpg",
	},	
	{
	  description: "Carnitine",
	  price: 30,
	  quantity: 100,
	  monthlyServingsNeed: 30,
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/now/now00068/l/5.jpg",
	},
	{
	  description: "Zinc",
	  price: 7,
	  quantity: 100,
	  monthlyServingsNeed: 30, 
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/clf/clf02951/w/9.jpg",
	},
	{
	  description: "CoQ10",
	  price: 12,
	  quantity: 120,
	  monthlyServingsNeed: 30, 
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/cgn/cgn00944/w/47.jpg",
	},
	{
	  description: "NAC",
	  price: 10,
	  quantity: 60,
	  monthlyServingsNeed: 30,
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/lex/lex15436/w/90.jpg",
	},
	{
	  description: "Vitamin D3",
	  price: 8,
	  quantity: 120,
	  monthlyServingsNeed: 30,
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/lex/lex15436/w/90.jpg",
	},
	{
	  description: "Magnesium",
	  price: 12,
	  quantity: 500,
	  monthlyServingsNeed: 90, 
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "amazon.co.uk",
	  photo: "https://images-na.ssl-images-amazon.com/images/I/61dRaF6xDML._SL1000_.jpg",
	},
	{
	  description: "Potassium",
	  price: 12,
	  quantity: 1000,
	  monthlyServingsNeed: 60, 
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "compagnie-bicarbonate.com"
	  photo: "https://www.compagnie-bicarbonate.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/i/bicarbonate_de_potassium_01.jpg",
	},
	{
	  description: "Calcium",
	  price: 23,
	  quantity: 1000,
	  monthlyServingsNeed: 60, 
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "amazon.co.uk",
	  photo: "https://images-na.ssl-images-amazon.com/images/I/61uD4Sah1ML._SL1500_.jpg",
	},
	{
	  description: "ALA",
	  price: 10,
	  quantity: 60,
	  monthlyServingsNeed: 30, 
	  pricePerServings: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/drb/drb00133/w/45.jpg",
	},
];
