export const micronutriments = [
	{
	  description: "Multivitamins",
	  price: 28,
	  quantity: 180,
	  servings: 360,
	  monthlyServingsNeed: 30,
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/now/now03881/y/6.jpg",
	},
	{
	  description: "Magnesium",
	  price: 12,
	  quantity: 500,
	  servings: 170,
	  monthlyServingsNeed: 90, 
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "amazon.co.uk",
	  photo: "https://images-na.ssl-images-amazon.com/images/I/61dRaF6xDML._SL1000_.jpg",
	},
	{
	  description: "Potassium",
	  price: 9,
	  quantity: 500,
	  servings: 200,
	  monthlyServingsNeed: 60, 
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "amazon.co.uk",
	  photo: "https://images-na.ssl-images-amazon.com/images/I/51jN5ImzdqL._SL1200_.jpg",
	},
	{
	  description: "Calcium",
	  price: 23,
	  quantity: 1000,
	  servings: 350,
	  monthlyServingsNeed: 60, 
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "amazon.co.uk",
	  photo: "https://images-na.ssl-images-amazon.com/images/I/61uD4Sah1ML._SL1500_.jpg",
	},
	{
	  description: "Omega 3",
	  price: 21,
	  quantity: 180,
	  servings: 45,
	  monthlyServingsNeed: 120,
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/now/now01662/l/4.jpg",
	},
	{
	  description: "Vitamin D3",
	  price: 8,
	  quantity: 120,
	  servings: 45,
	  monthlyServingsNeed: 30,
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/now/now00372/w/8.jpg",
	},	
	{
	  description: "Zinc",
	  price: 7,
	  quantity: 100,
	  servings: 100,
	  monthlyServingsNeed: 30, 
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/clf/clf02951/w/9.jpg",
	},
	{
	  description: "Carnitine",
	  price: 30,
	  quantity: 100,
	  servings: 100,
	  monthlyServingsNeed: 30,
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/now/now00068/l/5.jpg",
	},
	{
	  description: "CoQ10",
	  price: 12,
	  quantity: 120,
	  servings: 120,
	  monthlyServingsNeed: 30, 
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/cgn/cgn00944/w/47.jpg",
	},
	{
	  description: "NAC",
	  price: 10,
	  quantity: 60,
	  servings: 60,
	  monthlyServingsNeed: 30,
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/lex/lex15436/w/90.jpg",
	},
	{
	  description: "ALA",
	  price: 10,
	  quantity: 60,
	  servings: 60,
	  monthlyServingsNeed: 30, 
	  pricePerServing: null,
	  productLifetime: null,
	  monthlyCost: null,
	  percentage: null,
	  site: "iHerb",
	  photo: "https://s3.images-iherb.com/drb/drb00133/w/45.jpg",
	},
];

